/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/CORE/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/grid4.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Material.004']}
        geometry={nodes.Curve021.geometry}
        position={[-33.86, -6, -19.44]}
        scale={[277.84, 218, 277.84]}
      />
      <mesh
        material={materials['Material.005']}
        geometry={nodes.Curve064.geometry}
        position={[44.55, -6, -19.44]}
        scale={[277.84, 352.29, 277.84]}
      />
      <mesh
        material={materials['Material.003']}
        geometry={nodes.Curve126.geometry}
        position={[44.55, -6, 58.94]}
        scale={[277.84, 218, 277.84]}
      />
    </group>
  )
}

useGLTF.preload('/grid4.glb')
