/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/jc3d.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.Layer_1}
        geometry={nodes.Depth_Map001.geometry}
        scale={[-0.025, 0.025, 0.025]}
        rotation={[0,0.3,0]}
        position={[0,-5,0]}
      />
    </group>
  )
}

useGLTF.preload('/jc3d.glb')
